version: '2'

services:
    percona.5.7:
      image: mysql:5.7
      container_name: percona.5.7
      volumes:
        - /usr/local/var/mysql:/var/lib/mysql
        - ./conf.d/:/etc/mysql/conf.d/
      environment:
        - MYSQL_ROOT_PASSWORD=admin
      ports:
        - "3307:3306"
      networks:
        - docker-net
