services:

  # traefik container
  traefik:
    container_name: traefik
    image: traefik:v3.1
    # image: traefik:v2.11.0 # still in beta, use v2.9.6 for stable version
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # It's not recommended mounting the docker socket into a container -> see https://github.com/wollomatic/traefik2-hardened
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro # static traefik configuration
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro # dynamic traefik configuration
      - ./config/acme.json:/etc/traefik/acme.json # TLS certificate storage
    networks:
      - docker-net
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"

      # define basic auth middleware for dashboard
      # - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=foobar:$$2y$$05$$z2KwKI.GmZ43BbwfmPPKw.CSl3rqQ0OhzBbdom.orfsMVKGLW/Xeu" # CHANGE PASSWORD!! (user: foobar / pwd: foobar)
      # how to set a real password:
      # sudo apt-get install apache2-utils
      # htpasswd -Bnb username password | sed -e s/\\$/\\$\\$/g

      # define traefik dashboard router and service
      - "traefik.http.routers.traefik.rule=Host(`traefik.mukeshyadav.com`)" # change hostname!
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.entrypoints=https"
      # - "traefik.http.routers.traefik.middlewares=traefik-auth, secHeaders@file, autodetectContenttype@file"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
networks:
  docker-net:
    external: true
    name: docker-net
