version: '2'

services:
  mongodb:
    image: "mongo:3"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db
    networks:
      - docker-net

networks:
  docker-net:
    external: true
