#docker run -u zap -p  -i  zap.sh -daemon -host 0.0.0.0 -port 8080
version: '2'

services:
    zaproxy:
      image: owasp/zap2docker-stable
      container_name: zaproxy
      command: zap-webswing.sh
      ports:
        - 8080:8080
        - 8090:8090
