version: '2'
services:
  graylog:
    image: graylog2/server:2.1.2
    volumes:
      - /data/mongodb/journal:/usr/share/graylog/data/journal
      - /data/graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
#    links:
#      - mongodb:mongodb
#      - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
    networks:
      - docker-net

networks:
  docker-net:
    external: true


