version: '3.1'

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.4.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # TODO: Change this
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysqlS.rule=Host(`mysql.mukeshyadav.com`)"
      - "traefik.http.routers.mysqlS.entrypoints=https"
      - "traefik.http.routers.mysqlS.tls=true"
      - "traefik.http.routers.mysqlS.tls.certresolver=cloudflare"
      - "traefik.http.routers.mysqlS.tls.domains[0].main=*.mukeshyadav.com"
      - "traefik.http.routers.mysqlS.service=mysqlService"
      - "traefik.http.services.mysqlService.loadBalancer.server.port=3306"

networks:
  docker-net:
    external: true

volumes:
  data:
    external: true
