# docker exec -ti mysql:5.7 mysql -U root -ppassword
# docker network create -d host docker-net

version: '2'

services:
    mysql.5.7:
      image: mysql:5.7
      container_name: mysql.5.7
      volumes:
        - /data/mysql:/var/lib/mysql
#        - /usr/local/var/mysql:/var/lib/mysql
        - ./conf.d/:/etc/mysql/conf.d/
      environment:
        - MYSQL_ROOT_PASSWORD=admin
      ports:
        - "3306:3306"
      networks:
        - docker-net

networks:
  docker-net:
    external: true


