services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg16
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ${DATA_DIR}/pgdata:/home/postgres/pgdata/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    networks:
      - docker-net

  pgbouncer:
    image: rmccaffrey/pgbouncer:latest
    container_name: 'pgbouncer'
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@timescaledb:5432/${PG_DB}
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    volumes:
      - ./pgbouncer:/etc/pgbouncer
    depends_on:
      - timescaledb
    ports:
      - "5532:5432"
    networks:
      - docker-net
    restart: on-failure

networks:
  docker-net:
    external: true

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/pgdata