services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg18
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ${DATA_DIR}/pgdata:/home/postgres/pgdata/data
    environment:
      - POSTGRES_USER=${PG_USER:-pguser}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-pguser}
      - POSTGRES_DB=${PG_DB:-postgres}
    ports:
      - "5432:5432"
    networks:
      - docker-net

networks:
  docker-net:
    external: true

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/pgdata
