# docker exec -ti postgres psql jbl_scm -U root
# docker network create -d bridge docker-net
version: '3.4'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - ~/data/postgres:/var/lib/postgresql
    networks:
      - docker-net

networks:
  docker-net:
    external: true
