version: '2'

services:
    redis:
      image: redis:latest
      container_name: redis
      volumes:
        - /data/redis:/var/lib/redis
      ports:
        - "6379:6379"
      networks:
        - docker-net

networks:
  docker-net:
    external: true
